-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 10:48:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pb2b2324_zoowaakoopii18_
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pb2b2324_zoowaakoopii18_
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pb2b2324_zoowaakoopii18_` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pb2b2324_zoowaakoopii18_` ;

-- -----------------------------------------------------
-- Table `pb2b2324_zoowaakoopii18_`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pb2b2324_zoowaakoopii18_`.`user` (
  `userId` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pb2b2324_zoowaakoopii18_`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pb2b2324_zoowaakoopii18_`.`question` (
  `questionId` INT NOT NULL,
  `userId` INT NOT NULL,
  `userId` INT NOT NULL,
  `question` VARCHAR(500) NOT NULL,
  `questionDate` TINYINT NOT NULL,
  PRIMARY KEY (`questionId`, `userId`),
  INDEX `fk_question_user1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `pb2b2324_zoowaakoopii18_`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pb2b2324_zoowaakoopii18_`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pb2b2324_zoowaakoopii18_`.`answer` (
  `answerId` INT NOT NULL,
  `userId` INT NOT NULL,
  `questionId` INT NOT NULL,
  `userId` INT NOT NULL,
  `questionId` INT NOT NULL,
  `answer` VARCHAR(500) NOT NULL,
  `answerAccepted` TINYINT(1) NOT NULL,
  `answerVotes` TINYINT(1) NOT NULL,
  `answerSnippet` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`answerId`, `userId`, `questionId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `questionId_UNIQUE` (`questionId` ASC) VISIBLE,
  INDEX `fk_answer_question_idx` (`questionId` ASC) VISIBLE,
  INDEX `fk_answer_user1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question`
    FOREIGN KEY (`questionId`)
    REFERENCES `pb2b2324_zoowaakoopii18_`.`question` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `pb2b2324_zoowaakoopii18_`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
